### ISSUE TITLE
MPI_TRANSPORT_ALL hangs

### ISSUE THREAD

**Issue by marius311** [JuliaParallel/MPIClusterManagers.jl#14] opened 2020-04-13 22:34 UTC
I've reproduced this on two separate systems, but basically the following script hangs when run with `mpiexec -n 2`, ie the `start_main_loop` call never returns on the master process:

```julia
using MPI
using MPIClusterManagers

MPI.Init()
comm = MPI.COMM_WORLD
rank = MPI.Comm_rank(comm)

@show rank

@show MPIClusterManagers.start_main_loop(MPI_TRANSPORT_ALL)
```

If I change to `TCP_TRANSPORT_ALL`, then it works.

I've checked with OpenMPI v3.1.3 and v4.0.2, julia 1.3.1. and 1.4, and MPI.jl v0.13.0 and MPIClusterManagers v0.1.0. 

Does anyone else see this?

**Comment by simonbyrne** [comment] 2020-04-13 23:05
Yes, I think this is the same as #9. Something changed in Julia 1.3 which broke this, and I wasn’t able to figure it out.

**Comment by ViralBShah** [comment] 2020-04-19 17:58
I just ran into the same thing with Julia 1.4 on the example in the README.

```
viralbshah@antarctic:~$ mpirun -np 5 ./julia-1.4.0/bin/julia cman-transport.jl TCP
0.014434405 seconds for 100 loops of send-recv of array size 1000
1.02567798 seconds for 100 loops of send-recv of array size 1000000
viralbshah@antarctic:~$ mpirun -np 5 ./julia-1.4.0/bin/julia cman-transport.jl MPI
^C^Cviralbshah@antarctic:~$ 
```

**Comment by simonbyrne** [comment] 2020-04-20 04:29
Close as duplicate of #9.

**Closed** 2020-04-20 04:30 UTC
