### ISSUE TITLE
Running tests can't find mpiexec

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/MPIClusterManagers.jl#18] opened 2020-05-12 13:47 UTC
Testing on 1.5 which has the fixes necessary:

```
(@v1.5) pkg> test MPIClusterManagers
    Testing MPIClusterManagers
Status `/private/var/folders/rj/njz8jnv11637flz6vgnb6bz00000gp/T/jl_NSJBIo/Project.toml`
  [da04e1cc] MPI v0.14.0
  [e7922434] MPIClusterManagers v0.1.0
  [8ba89e20] Distributed
  [44cfe95a] Pkg
  [9e88b42a] Serialization
  [6462fe0b] Sockets
  [8dfed614] Test
Status `/private/var/folders/rj/njz8jnv11637flz6vgnb6bz00000gp/T/jl_NSJBIo/Manifest.toml`
  [e66e0078] CompilerSupportLibraries_jll v0.3.3+0
  [ffbed154] DocStringExtensions v0.8.1
  [da04e1cc] MPI v0.14.0
  [7cb0a576] MPICH_jll v3.3.2+9
  [e7922434] MPIClusterManagers v0.1.0
  [9237b28f] MicrosoftMPI_jll v10.1.2+3
  [fe0851c0] OpenMPI_jll v4.0.2+2
  [ae029012] Requires v1.0.1
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [b77e0a4c] InteractiveUtils
  [76f85450] LibGit2
  [8f399da3] Libdl
  [56ddb016] Logging
  [d6f4376e] Markdown
  [44cfe95a] Pkg
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA
  [9e88b42a] Serialization
  [6462fe0b] Sockets
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
Precompiling project...
ERROR: LoadError: IOError: could not spawn `mpiexec --version`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at ./process.jl:99
 [2] #581 at ./process.jl:112 [inlined]
 [3] setup_stdios(::Base.var"#581#582"{Cmd}, ::Array{Any,1}) at ./process.jl:196
 [4] _spawn at ./process.jl:111 [inlined]
 [5] open(::Cmd, ::Base.DevNull; write::Bool, read::Bool) at ./process.jl:370
 [6] open at ./process.jl:361 [inlined]
 [7] open(::Cmd, ::String, ::Base.DevNull) at ./process.jl:341
 [8] read(::Cmd) at ./process.jl:410
 [9] read(::Cmd, ::Type{String}) at ./process.jl:421
 [10] runtests() at /Users/viral/.julia/packages/MPIClusterManagers/HhXvP/test/runtests.jl:22
 [11] top-level scope at /Users/viral/.julia/packages/MPIClusterManagers/HhXvP/test/runtests.jl:42
 [12] include(::String) at ./client.jl:457
 [13] top-level scope at none:6
in expression starting at /Users/viral/.julia/packages/MPIClusterManagers/HhXvP/test/runtests.jl:42
ERROR: Package MPIClusterManagers errored during testing
```

**Comment by simonbyrne** [comment] 2020-05-12 14:06
Duplicate of #16.

**Closed by simonbyrne** 2020-05-12 14:06 UTC
